name: Publish to NPM

on:
    release:
        types: [created]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - run: pnpm install --frozen-lockfile

            - name: Create Release Pull Request
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
